# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '17 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale because there has been no activity for more than 6 months. If no update is made, this issue will be closed in 14 days.'
        stale-pr-message: 'This pull request has been marked as stale because there has been no activity for more than 6 months. If no update is made, this pull request will be closed in 14 days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'enhancement,help wanted'
        days-before-stale: 180
        days-before-close: 14
        exempt-all-milestones: true
